# Changes here will be overwritten by Copier
_commit: 1.1.2
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
copyright_license: GNU General Public License v3.0
project_description: The API offer simple text to speach functionality based on PIPER.
project_name: TTS Batch API
python_package_distribution_name: tts-batch-api
python_package_import_name: app
version: 2.2.1
