name: Release Please

on:
  # Temporarily disabled during commit history cleanup
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Manual trigger only

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: actions/create-github-app-token@v2
        id: generate_token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: python
